### ISSUE TITLE
So Pretty!! 

### ISSUE THREAD

**Issue by mimishahzad** [mbeckrich/obsidian#1]
@mbeckrich, your theme does Catppuccin so much justice, it's so clean and I absolutely love it! The only thing that I've found myself changing (and this is just preference for me) is the heading colors, which I prefer in a specific order, and the italic and bold styles. Again these are purely based on preference. I love this version of it though, it's literally perfect! 🤩

![image](https://user-images.githubusercontent.com/34081810/152074300-00aafa3a-519a-4bb1-96ce-431402096899.png)

**Comment by mbeckrich** [comment]
Thanks! I love the colors. If you don't mind, I'll plan on adding them in as defaults once I get Style Settings setup in the theme.

**Comment by mimishahzad** [comment]
go right ahead, it's literally beautiful! Thanks for working on this! 😄
